import { Sponsor } from '../types';

export const SPONSOR_DATA: Sponsor[] = [
    // Tier 1: Global Giants (High Rep)
    { id: 1, name: "Zenith Automotivo", tier: 1, guidelines: [{ type: 'min_reputation', value: 85 }, { type: 'prefers_champions' }], baseAnnualValue: [15_000_000, 30_000_000], preferredType: 'Camisa Principal' },
    { id: 2, name: "Tecnologia QuantumLeap", tier: 1, guidelines: [{ type: 'min_reputation', value: 80 }], baseAnnualValue: [10_000_000, 25_000_000], preferredType: 'Camisa Principal' },
    { id: 3, name: "AeroLeap Dynamics", tier: 1, guidelines: [{ type: 'min_reputation', value: 82 }], baseAnnualValue: [12_000_000, 28_000_000], preferredType: 'Camisa Principal' },
    { id: 4, name: "Apex Sportswear", tier: 1, guidelines: [{ type: 'min_reputation', value: 75 }], baseAnnualValue: [8_000_000, 20_000_000], preferredType: 'Fornecedor de Material' },
    { id: 5, name: "Banco Estelar Global", tier: 1, guidelines: [{ type: 'min_reputation', value: 88 }], baseAnnualValue: [18_000_000, 35_000_000], preferredType: 'Direitos do Estádio' },
    { id: 6, name: "Velocity Air", tier: 1, guidelines: [{ type: 'min_reputation', value: 80 }], baseAnnualValue: [9_000_000, 22_000_000], preferredType: 'Camisa Principal' },
    { id: 7, name: "Nexus Gaming", tier: 1, guidelines: [{ type: 'min_reputation', value: 78 }], baseAnnualValue: [7_000_000, 18_000_000], preferredType: 'Camisa Principal' },
    { id: 8, name: "Olympus Vestuário", tier: 1, guidelines: [{ type: 'min_reputation', value: 80 }], baseAnnualValue: [10_000_000, 25_000_000], preferredType: 'Fornecedor de Material' },
    { id: 9, name: "Horizon Telecom", tier: 1, guidelines: [{ type: 'min_reputation', value: 85 }], baseAnnualValue: [14_000_000, 26_000_000], preferredType: 'Camisa Principal' },
    { id: 10, name: "Momentum Motors", tier: 1, guidelines: [{ type: 'min_reputation', value: 83 }], baseAnnualValue: [11_000_000, 24_000_000], preferredType: 'Camisa Principal' },

    // Tier 2: National Brands (Mid-High Rep)
    { id: 11, name: "Construtora Pinnacle", tier: 2, guidelines: [{ type: 'min_reputation', value: 65 }], baseAnnualValue: [3_000_000, 8_000_000], preferredType: 'Camisa Principal' },
    { id: 12, name: "Energético Fusion", tier: 2, guidelines: [{ type: 'min_reputation', value: 60 }], baseAnnualValue: [2_500_000, 7_000_000], preferredType: 'Camisa Principal' },
    { id: 13, name: "Unity Sport", tier: 2, guidelines: [{ type: 'min_reputation', value: 60 }], baseAnnualValue: [2_000_000, 6_000_000], preferredType: 'Fornecedor de Material' },
    { id: 14, name: "ConnectNet Banda Larga", tier: 2, guidelines: [{ type: 'min_reputation', value: 68 }], baseAnnualValue: [4_000_000, 9_000_000], preferredType: 'Camisa Principal' },
    { id: 15, name: "Seguros Heritage", tier: 2, guidelines: [{ type: 'min_reputation', value: 70 }], baseAnnualValue: [5_000_000, 12_000_000], preferredType: 'Direitos do Estádio' },
    { id: 16, name: "Padaria Golden Crust", tier: 2, guidelines: [{ type: 'min_reputation', value: 55 }], baseAnnualValue: [1_000_000, 4_000_000], preferredType: 'Camisa Principal' },
    { id: 17, name: "Ferramentas Titan", tier: 2, guidelines: [{ type: 'min_reputation', value: 62 }], baseAnnualValue: [2_800_000, 6_500_000], preferredType: 'Camisa Principal' },
    { id: 18, name: "Logística Vertex", tier: 2, guidelines: [{ type: 'min_reputation', value: 65 }], baseAnnualValue: [3_200_000, 7_500_000], preferredType: 'CT' },
    { id: 19, name: "Patriot Sportswear", tier: 2, guidelines: [{ type: 'min_reputation', value: 65 }, { type: 'country', value: 'Brasil' }], baseAnnualValue: [3_000_000, 8_000_000], preferredType: 'Fornecedor de Material' },
    { id: 20, name: "Ferrovia Nacional", tier: 2, guidelines: [{ type: 'min_reputation', value: 70 }], baseAnnualValue: [4_500_000, 10_000_000], preferredType: 'Camisa Principal' },
    { id: 21, name: "Academias Pro-Fit", tier: 2, guidelines: [{ type: 'min_reputation', value: 60 }], baseAnnualValue: [1_500_000, 5_000_000], preferredType: 'CT' },
    { id: 22, name: "Soluções Byte-Force", tier: 2, guidelines: [{ type: 'min_reputation', value: 70 }], baseAnnualValue: [4_000_000, 9_000_000], preferredType: 'Camisa Principal' },
    { id: 23, name: "Capital Investimentos", tier: 2, guidelines: [{ type: 'min_reputation', value: 75 }], baseAnnualValue: [6_000_000, 15_000_000], preferredType: 'Camisa Principal' },
    { id: 24, name: "Hotéis Regal", tier: 2, guidelines: [{ type: 'min_reputation', value: 68 }], baseAnnualValue: [3_500_000, 8_500_000], preferredType: 'Camisa Principal' },
    { id: 25, name: "Relógios Sovereign", tier: 2, guidelines: [{ type: 'min_reputation', value: 72 }], baseAnnualValue: [5_500_000, 11_000_000], preferredType: 'Camisa Principal' },
    
    // Tier 3: Regional / Challenger Brands (Low-Mid Rep)
    { id: 26, name: "Construtora Riverdale", tier: 3, guidelines: [{ type: 'min_reputation', value: 50 }, { type: 'max_reputation', value: 75 }], baseAnnualValue: [500_000, 2_000_000], preferredType: 'Camisa Principal' },
    { id: 27, name: "Grit Athletics", tier: 3, guidelines: [{ type: 'min_reputation', value: 45 }, { type: 'max_reputation', value: 70 }, { type: 'prefers_underdogs' }], baseAnnualValue: [400_000, 1_500_000], preferredType: 'Fornecedor de Material' },
    { id: 28, name: "Transportadora Eastwood", tier: 3, guidelines: [{ type: 'min_reputation', value: 50 }, { type: 'max_reputation', value: 72 }], baseAnnualValue: [600_000, 2_200_000], preferredType: 'Camisa Principal' },
    { id: 29, name: "Advocacia Silverstone", tier: 3, guidelines: [{ type: 'min_reputation', value: 55 }, { type: 'max_reputation', value: 78 }], baseAnnualValue: [700_000, 2_500_000], preferredType: 'Camisa Principal' },
    { id: 30, name: "Imobiliária Oakstead", tier: 3, guidelines: [{ type: 'min_reputation', value: 50 }, { type: 'max_reputation', value: 75 }], baseAnnualValue: [800_000, 3_000_000], preferredType: 'Direitos do Estádio' },
    { id: 31, name: "Navegador GPS", tier: 3, guidelines: [{ type: 'min_reputation', value: 58 }, { type: 'max_reputation', value: 78 }], baseAnnualValue: [900_000, 3_500_000], preferredType: 'Camisa Principal' },
    { id: 32, name: "Sparkle Cola", tier: 3, guidelines: [{ type: 'min_reputation', value: 55 }, { type: 'max_reputation', value: 75 }], baseAnnualValue: [750_000, 2_800_000], preferredType: 'Camisa Principal' },
    { id: 33, name: "Uniformes Rhino", tier: 3, guidelines: [{ type: 'min_reputation', value: 50 }, { type: 'max_reputation', value: 70 }], baseAnnualValue: [450_000, 1_800_000], preferredType: 'Fornecedor de Material' },
    { id: 34, name: "Meridian Shipping", tier: 3, guidelines: [{ type: 'min_reputation', value: 60 }, { type: 'max_reputation', value: 80 }], baseAnnualValue: [1_200_000, 4_000_000], preferredType: 'Camisa Principal' },
    { id: 35, name: "Água BlueMountain", tier: 3, guidelines: [{ type: 'min_reputation', value: 50 }, { type: 'max_reputation', value: 75 }], baseAnnualValue: [550_000, 2_100_000], preferredType: 'CT' },
    { id: 36, name: "Academias Forge", tier: 3, guidelines: [{ type: 'min_reputation', value: 52 }, { type: 'max_reputation', value: 72 }], baseAnnualValue: [650_000, 2_400_000], preferredType: 'CT' },
    { id: 37, name: "Segurança Centurion", tier: 3, guidelines: [{ type: 'min_reputation', value: 55 }, { type: 'max_reputation', value: 78 }], baseAnnualValue: [850_000, 3_200_000], preferredType: 'Camisa Principal' },
    { id: 38, name: "Innovate Software", tier: 3, guidelines: [{ type: 'min_reputation', value: 60 }, { type: 'max_reputation', value: 80 }], baseAnnualValue: [1_500_000, 4_500_000], preferredType: 'Camisa Principal' },
    { id: 39, name: "Academias Ironclad", tier: 3, guidelines: [{ type: 'min_reputation', value: 50 }, { type: 'max_reputation', value: 70 }], baseAnnualValue: [500_000, 1_900_000], preferredType: 'CT' },
    { id: 40, name: "Summit Sports", tier: 3, guidelines: [{ type: 'min_reputation', value: 55 }, { type: 'max_reputation', value: 75 }], baseAnnualValue: [800_000, 2_700_000], preferredType: 'Fornecedor de Material' },

    // Tier 4: Local Businesses (Low Rep)
    { id: 41, name: "Bar do Zé", tier: 4, guidelines: [{ type: 'max_reputation', value: 60 }], baseAnnualValue: [50_000, 200_000], preferredType: 'Camisa Principal' },
    { id: 42, name: "Salsichas da Vila", tier: 4, guidelines: [{ type: 'max_reputation', value: 55 }], baseAnnualValue: [40_000, 150_000], preferredType: 'Camisa Principal' },
    { id: 43, name: "Advogados & Associados", tier: 4, guidelines: [{ type: 'max_reputation', value: 62 }], baseAnnualValue: [70_000, 250_000], preferredType: 'Camisa Principal' },
    { id: 44, name: "CrediAmigo", tier: 4, guidelines: [{ type: 'max_reputation', value: 65 }], baseAnnualValue: [100_000, 400_000], preferredType: 'Direitos do Estádio' },
    { id: 45, name: "Pneus Bridgewater", tier: 4, guidelines: [{ type: 'max_reputation', value: 58 }], baseAnnualValue: [60_000, 220_000], preferredType: 'Camisa Principal' },
    { id: 46, name: "Açougue do Lago", tier: 4, guidelines: [{ type: 'max_reputation', value: 55 }], baseAnnualValue: [30_000, 120_000], preferredType: 'Camisa Principal' },
    { id: 47, name: "Peixaria do Porto", tier: 4, guidelines: [{ type: 'max_reputation', value: 57 }], baseAnnualValue: [45_000, 180_000], preferredType: 'Camisa Principal' },
    { id: 48, name: "Táxis Westfield", tier: 4, guidelines: [{ type: 'max_reputation', value: 60 }], baseAnnualValue: [80_000, 300_000], preferredType: 'Camisa Principal' },
    { id: 49, name: "Cervejaria da Gávea", tier: 4, guidelines: [{ type: 'max_reputation', value: 62 }], baseAnnualValue: [90_000, 350_000], preferredType: 'Camisa Principal' },
    { id: 50, name: "Andaimes Topo do Mundo", tier: 4, guidelines: [{ type: 'max_reputation', value: 55 }], baseAnnualValue: [55_000, 210_000], preferredType: 'CT' },
    { id: 51, name: "Eletricista Easton", tier: 4, guidelines: [{ type: 'max_reputation', value: 58 }], baseAnnualValue: [65_000, 230_000], preferredType: 'Camisa Principal' },
    { id: 52, name: "Fazenda Vale Verde", tier: 4, guidelines: [{ type: 'max_reputation', value: 55 }], baseAnnualValue: [35_000, 140_000], preferredType: 'Camisa Principal' },
    { id: 53, name: "Uniforme da Galera", tier: 4, guidelines: [{ type: 'max_reputation', value: 60 }, { type: 'prefers_underdogs' }], baseAnnualValue: [80_000, 300_000], preferredType: 'Fornecedor de Material' },
    { id: 54, name: "Jornal da Cidade", tier: 4, guidelines: [{ type: 'max_reputation', value: 65 }], baseAnnualValue: [120_000, 450_000], preferredType: 'Direitos do Estádio' },
    { id: 55, name: "Suporte TI Riverdale", tier: 4, guidelines: [{ type: 'max_reputation', value: 60 }], baseAnnualValue: [75_000, 280_000], preferredType: 'Camisa Principal' },
    { id: 56, name: "Jardinagem Sempre Verde", tier: 4, guidelines: [{ type: 'max_reputation', value: 55 }], baseAnnualValue: [25_000, 100_000], preferredType: 'Camisa Principal' },
    { id: 57, name: "Motores de Confiança", tier: 4, guidelines: [{ type: 'max_reputation', value: 62 }], baseAnnualValue: [110_000, 420_000], preferredType: 'Camisa Principal' },
    { id: 58, name: "Construtora & Filhos", tier: 4, guidelines: [{ type: 'max_reputation', value: 58 }], baseAnnualValue: [85_000, 310_000], preferredType: 'CT' },
    { id: 59, name: "Café da Esquina", tier: 4, guidelines: [{ type: 'max_reputation', value: 50 }], baseAnnualValue: [20_000, 80_000], preferredType: 'Camisa Principal' },
    { id: 60, name: "Floricultura do Centro", tier: 4, guidelines: [{ type: 'max_reputation', value: 52 }], baseAnnualValue: [22_000, 90_000], preferredType: 'Camisa Principal' },
    { id: 61, name: "Gráfica Digital Dinâmica", tier: 4, guidelines: [{ type: 'max_reputation', value: 60 }], baseAnnualValue: [95_000, 330_000], preferredType: 'Camisa Principal' },
    { id: 62, name: "Segurança Alpha", tier: 4, guidelines: [{ type: 'max_reputation', value: 65 }], baseAnnualValue: [130_000, 500_000], preferredType: 'Direitos do Estádio' },
    { id: 63, name: "Academia do Povo", tier: 4, guidelines: [{ type: 'max_reputation', value: 58 }], baseAnnualValue: [70_000, 260_000], preferredType: 'CT' },
    { id: 64, name: "Mercadinho Rápido", tier: 4, guidelines: [{ type: 'max_reputation', value: 50 }], baseAnnualValue: [15_000, 75_000], preferredType: 'Camisa Principal' },
    { id: 65, name: "Agência de Viagens Centro", tier: 4, guidelines: [{ type: 'max_reputation', value: 55 }], baseAnnualValue: [40_000, 160_000], preferredType: 'Camisa Principal' },
    { id: 66, name: "Hotel Kings Head", tier: 4, guidelines: [{ type: 'max_reputation', value: 60 }], baseAnnualValue: [100_000, 380_000], preferredType: 'Camisa Principal' },
    { id: 67, "name": "Correio Regional", "tier": 4, "guidelines": [{ "type": "max_reputation", "value": 64 }], "baseAnnualValue": [115000, 430000], "preferredType": "Camisa Principal" },
    { id: 68, name: "Ambição Sportswear", tier: 4, guidelines: [{ type: 'max_reputation', value: 65 }, { type: 'prefers_underdogs' }], baseAnnualValue: [150_000, 550_000], preferredType: 'Fornecedor de Material' },
    { id: 69, name: "Café Nascer do Sol", tier: 4, guidelines: [{ type: 'max_reputation', value: 55 }], baseAnnualValue: [50_000, 190_000], preferredType: 'Camisa Principal' },
    { id: 70, name: "Vertex Solar", tier: 4, guidelines: [{ type: 'max_reputation', value: 62 }], baseAnnualValue: [125_000, 480_000], preferredType: 'CT' },
    { id: 71, name: "Seguros do Porto", tier: 4, guidelines: [{ type: 'max_reputation', value: 60 }], baseAnnualValue: [100_000, 370_000], preferredType: 'Camisa Principal' },
    { id: 72, name: "Engenharia de Precisão", tier: 4, guidelines: [{ type: 'max_reputation', value: 63 }], baseAnnualValue: [140_000, 520_000], preferredType: 'Camisa Principal' },
    { id: 73, name: "Feira do Produtor", tier: 4, guidelines: [{ type: 'max_reputation', value: 50 }], baseAnnualValue: [18_000, 85_000], preferredType: 'Camisa Principal' },
    { id: 74, name: "Prefeitura Municipal", tier: 4, guidelines: [{ type: 'max_reputation', value: 68 }], baseAnnualValue: [200_000, 700_000], preferredType: 'Direitos do Estádio' },
    { id: 75, name: "Encanador a Jato", tier: 4, guidelines: [{ type: 'max_reputation', value: 55 }], baseAnnualValue: [48_000, 170_000], preferredType: 'Camisa Principal' },
    { id: 76, name: "Entregas Jato", tier: 4, guidelines: [{ type: 'max_reputation', value: 60 }], baseAnnualValue: [98_000, 360_000], preferredType: 'Camisa Principal' },
    { id: 77, name: "Açougue do Bairro", tier: 4, guidelines: [{ type: 'max_reputation', value: 53 }], baseAnnualValue: [28_000, 110_000], preferredType: 'Camisa Principal' },
    { id: 78, name: "Padaria Alvorada", tier: 4, guidelines: [{ type: 'max_reputation', value: 54 }], baseAnnualValue: [32_000, 130_000], preferredType: 'Camisa Principal' },
    { id: 79, name: "Banco da Comunidade", tier: 4, guidelines: [{ type: 'max_reputation', value: 65 }], baseAnnualValue: [180_000, 650_000], preferredType: 'Camisa Principal' },
    { id: 80, name: "Aeroporto da Cidade", tier: 4, guidelines: [{ type: 'max_reputation', value: 66 }], baseAnnualValue: [220_000, 800_000], preferredType: 'CT' }
];