import { Sponsor } from '../types';

export const SPONSOR_DATA: Sponsor[] = [
    // Tier 1: Global Giants (High Rep)
    { id: 1, name: "Zenith Automotive", tier: 1, guidelines: [{ type: 'min_reputation', value: 85 }, { type: 'prefers_champions' }], baseAnnualValue: [15_000_000, 30_000_000], preferredType: 'Main Shirt' },
    { id: 2, name: "QuantumLeap Tech", tier: 1, guidelines: [{ type: 'min_reputation', value: 80 }], baseAnnualValue: [10_000_000, 25_000_000], preferredType: 'Main Shirt' },
    { id: 3, name: "AeroLeap Dynamics", tier: 1, guidelines: [{ type: 'min_reputation', value: 82 }], baseAnnualValue: [12_000_000, 28_000_000], preferredType: 'Main Shirt' },
    { id: 4, name: "Apex Sportswear", tier: 1, guidelines: [{ type: 'min_reputation', value: 75 }], baseAnnualValue: [8_000_000, 20_000_000], preferredType: 'Kit Supplier' },
    { id: 5, name: "Stellar Bank Global", tier: 1, guidelines: [{ type: 'min_reputation', value: 88 }], baseAnnualValue: [18_000_000, 35_000_000], preferredType: 'Stadium Naming Rights' },
    { id: 6, name: "Velocity Air", tier: 1, guidelines: [{ type: 'min_reputation', value: 80 }], baseAnnualValue: [9_000_000, 22_000_000], preferredType: 'Main Shirt' },
    { id: 7, name: "Nexus Gaming", tier: 1, guidelines: [{ type: 'min_reputation', value: 78 }], baseAnnualValue: [7_000_000, 18_000_000], preferredType: 'Main Shirt' },
    { id: 8, name: "Olympus Apparel", tier: 1, guidelines: [{ type: 'min_reputation', value: 80 }], baseAnnualValue: [10_000_000, 25_000_000], preferredType: 'Kit Supplier' },
    { id: 9, name: "Horizon Telecom", tier: 1, guidelines: [{ type: 'min_reputation', value: 85 }], baseAnnualValue: [14_000_000, 26_000_000], preferredType: 'Main Shirt' },
    { id: 10, name: "Momentum Motors", tier: 1, guidelines: [{ type: 'min_reputation', value: 83 }], baseAnnualValue: [11_000_000, 24_000_000], preferredType: 'Main Shirt' },

    // Tier 2: National Brands (Mid-High Rep)
    { id: 11, name: "Pinnacle Construction", tier: 2, guidelines: [{ type: 'min_reputation', value: 65 }], baseAnnualValue: [3_000_000, 8_000_000], preferredType: 'Main Shirt' },
    { id: 12, name: "Fusion Energy Drink", tier: 2, guidelines: [{ type: 'min_reputation', value: 60 }], baseAnnualValue: [2_500_000, 7_000_000], preferredType: 'Main Shirt' },
    { id: 13, name: "Unity Sport", tier: 2, guidelines: [{ type: 'min_reputation', value: 60 }], baseAnnualValue: [2_000_000, 6_000_000], preferredType: 'Kit Supplier' },
    { id: 14, name: "ConnectNet Broadband", tier: 2, guidelines: [{ type: 'min_reputation', value: 68 }], baseAnnualValue: [4_000_000, 9_000_000], preferredType: 'Main Shirt' },
    { id: 15, name: "Heritage Insurance", tier: 2, guidelines: [{ type: 'min_reputation', value: 70 }], baseAnnualValue: [5_000_000, 12_000_000], preferredType: 'Stadium Naming Rights' },
    { id: 16, name: "Golden Crust Bakery", tier: 2, guidelines: [{ type: 'min_reputation', value: 55 }], baseAnnualValue: [1_000_000, 4_000_000], preferredType: 'Main Shirt' },
    { id: 17, name: "Titan Tools", tier: 2, guidelines: [{ type: 'min_reputation', value: 62 }], baseAnnualValue: [2_800_000, 6_500_000], preferredType: 'Main Shirt' },
    { id: 18, name: "Vertex Logistics", tier: 2, guidelines: [{ type: 'min_reputation', value: 65 }], baseAnnualValue: [3_200_000, 7_500_000], preferredType: 'Training Ground' },
    { id: 19, name: "Patriot Sportswear", tier: 2, guidelines: [{ type: 'min_reputation', value: 65 }, { type: 'country', value: 'England' }], baseAnnualValue: [3_000_000, 8_000_000], preferredType: 'Kit Supplier' },
    { id: 20, name: "National Rail Co.", tier: 2, guidelines: [{ type: 'min_reputation', value: 70 }], baseAnnualValue: [4_500_000, 10_000_000], preferredType: 'Main Shirt' },
    { id: 21, name: "Pro-Fit Gyms", tier: 2, guidelines: [{ type: 'min_reputation', value: 60 }], baseAnnualValue: [1_500_000, 5_000_000], preferredType: 'Training Ground' },
    { id: 22, name: "Byte-Force Solutions", tier: 2, guidelines: [{ type: 'min_reputation', value: 70 }], baseAnnualValue: [4_000_000, 9_000_000], preferredType: 'Main Shirt' },
    { id: 23, name: "Capital Investments", tier: 2, guidelines: [{ type: 'min_reputation', value: 75 }], baseAnnualValue: [6_000_000, 15_000_000], preferredType: 'Main Shirt' },
    { id: 24, name: "Regal Hotels", tier: 2, guidelines: [{ type: 'min_reputation', value: 68 }], baseAnnualValue: [3_500_000, 8_500_000], preferredType: 'Main Shirt' },
    { id: 25, name: "Sovereign Watches", tier: 2, guidelines: [{ type: 'min_reputation', value: 72 }], baseAnnualValue: [5_500_000, 11_000_000], preferredType: 'Main Shirt' },
    
    // Tier 3: Regional / Challenger Brands (Low-Mid Rep)
    { id: 26, name: "Riverdale Construction", tier: 3, guidelines: [{ type: 'min_reputation', value: 50 }, { type: 'max_reputation', value: 75 }], baseAnnualValue: [500_000, 2_000_000], preferredType: 'Main Shirt' },
    { id: 27, name: "Grit Athletics", tier: 3, guidelines: [{ type: 'min_reputation', value: 45 }, { type: 'max_reputation', value: 70 }, { type: 'prefers_underdogs' }], baseAnnualValue: [400_000, 1_500_000], preferredType: 'Kit Supplier' },
    { id: 28, name: "Eastwood Haulage", tier: 3, guidelines: [{ type: 'min_reputation', value: 50 }, { type: 'max_reputation', value: 72 }], baseAnnualValue: [600_000, 2_200_000], preferredType: 'Main Shirt' },
    { id: 29, name: "Silverstone Legal", tier: 3, guidelines: [{ type: 'min_reputation', value: 55 }, { type: 'max_reputation', value: 78 }], baseAnnualValue: [700_000, 2_500_000], preferredType: 'Main Shirt' },
    { id: 30, name: "Oakstead Realty", tier: 3, guidelines: [{ type: 'min_reputation', value: 50 }, { type: 'max_reputation', value: 75 }], baseAnnualValue: [800_000, 3_000_000], preferredType: 'Stadium Naming Rights' },
    { id: 31, name: "Navigator GPS", tier: 3, guidelines: [{ type: 'min_reputation', value: 58 }, { type: 'max_reputation', value: 78 }], baseAnnualValue: [900_000, 3_500_000], preferredType: 'Main Shirt' },
    { id: 32, name: "Sparkle Cola", tier: 3, guidelines: [{ type: 'min_reputation', value: 55 }, { type: 'max_reputation', value: 75 }], baseAnnualValue: [750_000, 2_800_000], preferredType: 'Main Shirt' },
    { id: 33, name: "Rhino Workwear", tier: 3, guidelines: [{ type: 'min_reputation', value: 50 }, { type: 'max_reputation', value: 70 }], baseAnnualValue: [450_000, 1_800_000], preferredType: 'Kit Supplier' },
    { id: 34, name: "Meridian Shipping", tier: 3, guidelines: [{ type: 'min_reputation', value: 60 }, { type: 'max_reputation', value: 80 }], baseAnnualValue: [1_200_000, 4_000_000], preferredType: 'Main Shirt' },
    { id: 35, name: "BlueMountain Water", tier: 3, guidelines: [{ type: 'min_reputation', value: 50 }, { type: 'max_reputation', value: 75 }], baseAnnualValue: [550_000, 2_100_000], preferredType: 'Training Ground' },
    { id: 36, name: "Forge Fitness", tier: 3, guidelines: [{ type: 'min_reputation', value: 52 }, { type: 'max_reputation', value: 72 }], baseAnnualValue: [650_000, 2_400_000], preferredType: 'Training Ground' },
    { id: 37, name: "Centurion Security", tier: 3, guidelines: [{ type: 'min_reputation', value: 55 }, { type: 'max_reputation', value: 78 }], baseAnnualValue: [850_000, 3_200_000], preferredType: 'Main Shirt' },
    { id: 38, name: "Innovate Software", tier: 3, guidelines: [{ type: 'min_reputation', value: 60 }, { type: 'max_reputation', value: 80 }], baseAnnualValue: [1_500_000, 4_500_000], preferredType: 'Main Shirt' },
    { id: 39, name: "Ironclad Gyms", tier: 3, guidelines: [{ type: 'min_reputation', value: 50 }, { type: 'max_reputation', value: 70 }], baseAnnualValue: [500_000, 1_900_000], preferredType: 'Training Ground' },
    { id: 40, name: "Summit Sports", tier: 3, guidelines: [{ type: 'min_reputation', value: 55 }, { type: 'max_reputation', value: 75 }], baseAnnualValue: [800_000, 2_700_000], preferredType: 'Kit Supplier' },

    // Tier 4: Local Businesses (Low Rep)
    { id: 41, name: "The Anchor Pub", tier: 4, guidelines: [{ type: 'max_reputation', value: 60 }], baseAnnualValue: [50_000, 200_000], preferredType: 'Main Shirt' },
    { id: 42, name: "Northwood Sausages", tier: 4, guidelines: [{ type: 'max_reputation', value: 55 }], baseAnnualValue: [40_000, 150_000], preferredType: 'Main Shirt' },
    { id: 43, name: "Fairview Solicitors", tier: 4, guidelines: [{ type: 'max_reputation', value: 62 }], baseAnnualValue: [70_000, 250_000], preferredType: 'Main Shirt' },
    { id: 44, name: "Oakhaven Credit Union", tier: 4, guidelines: [{ type: 'max_reputation', value: 65 }], baseAnnualValue: [100_000, 400_000], preferredType: 'Stadium Naming Rights' },
    { id: 45, name: "Bridgewater Tyres", tier: 4, guidelines: [{ type: 'max_reputation', value: 58 }], baseAnnualValue: [60_000, 220_000], preferredType: 'Main Shirt' },
    { id: 46, name: "Lakeside Butchers", tier: 4, guidelines: [{ type: 'max_reputation', value: 55 }], baseAnnualValue: [30_000, 120_000], preferredType: 'Main Shirt' },
    { id: 47, name: "Portsmith Fish & Chips", tier: 4, guidelines: [{ type: 'max_reputation', value: 57 }], baseAnnualValue: [45_000, 180_000], preferredType: 'Main Shirt' },
    { id: 48, name: "Westfield Cabs", tier: 4, guidelines: [{ type: 'max_reputation', value: 60 }], baseAnnualValue: [80_000, 300_000], preferredType: 'Main Shirt' },
    { id: 49, name: "Southglen Brewery", tier: 4, guidelines: [{ type: 'max_reputation', value: 62 }], baseAnnualValue: [90_000, 350_000], preferredType: 'Main Shirt' },
    { id: 50, name: "Mountview Scaffolding", tier: 4, guidelines: [{ type: 'max_reputation', value: 55 }], baseAnnualValue: [55_000, 210_000], preferredType: 'Training Ground' },
    { id: 51, name: "Easton Electrical", tier: 4, guidelines: [{ type: 'max_reputation', value: 58 }], baseAnnualValue: [65_000, 230_000], preferredType: 'Main Shirt' },
    { id: 52, name: "Valley View Farm", tier: 4, guidelines: [{ type: 'max_reputation', value: 55 }], baseAnnualValue: [35_000, 140_000], preferredType: 'Main Shirt' },
    { id: 53, name: "Local Lads Kit", tier: 4, guidelines: [{ type: 'max_reputation', value: 60 }, { type: 'prefers_underdogs' }], baseAnnualValue: [80_000, 300_000], preferredType: 'Kit Supplier' },
    { id: 54, name: "The Town Crier News", tier: 4, guidelines: [{ type: 'max_reputation', value: 65 }], baseAnnualValue: [120_000, 450_000], preferredType: 'Stadium Naming Rights' },
    { id: 55, name: "Riverdale IT Support", tier: 4, guidelines: [{ type: 'max_reputation', value: 60 }], baseAnnualValue: [75_000, 280_000], preferredType: 'Main Shirt' },
    { id: 56, name: "Evergreen Gardening", tier: 4, guidelines: [{ type: 'max_reputation', value: 55 }], baseAnnualValue: [25_000, 100_000], preferredType: 'Main Shirt' },
    { id: 57, name: "Trusty Motors", tier: 4, guidelines: [{ type: 'max_reputation', value: 62 }], baseAnnualValue: [110_000, 420_000], preferredType: 'Main Shirt' },
    { id: 58, name: "Gable & Sons Builders", tier: 4, guidelines: [{ type: 'max_reputation', value: 58 }], baseAnnualValue: [85_000, 310_000], preferredType: 'Training Ground' },
    { id: 59, name: "The Corner Cafe", tier: 4, guidelines: [{ type: 'max_reputation', value: 50 }], baseAnnualValue: [20_000, 80_000], preferredType: 'Main Shirt' },
    { id: 60, name: "City Centre Florist", tier: 4, guidelines: [{ type: 'max_reputation', value: 52 }], baseAnnualValue: [22_000, 90_000], preferredType: 'Main Shirt' },
    { id: 61, name: "Dynamic Digital Print", tier: 4, guidelines: [{ type: 'max_reputation', value: 60 }], baseAnnualValue: [95_000, 330_000], preferredType: 'Main Shirt' },
    { id: 62, name: "Alpha Security", tier: 4, guidelines: [{ type: 'max_reputation', value: 65 }], baseAnnualValue: [130_000, 500_000], preferredType: 'Stadium Naming Rights' },
    { id: 63, name: "The People's Gym", tier: 4, guidelines: [{ type: 'max_reputation', value: 58 }], baseAnnualValue: [70_000, 260_000], preferredType: 'Training Ground' },
    { id: 64, name: "Quickie Mart", tier: 4, guidelines: [{ type: 'max_reputation', value: 50 }], baseAnnualValue: [15_000, 75_000], preferredType: 'Main Shirt' },
    { id: 65, name: "Main Street Travel", tier: 4, guidelines: [{ type: 'max_reputation', value: 55 }], baseAnnualValue: [40_000, 160_000], preferredType: 'Main Shirt' },
    { id: 66, name: "Kings Head Hotel", tier: 4, guidelines: [{ type: 'max_reputation', value: 60 }], baseAnnualValue: [100_000, 380_000], preferredType: 'Main Shirt' },
    { id: 67, name: "Regional Post", tier: 4, guidelines: [{ type: 'max_reputation', value: 64 }], baseAnnualValue: [115_000, 430_000], preferredType: 'Main Shirt' },
    { id: 68, name: "Ambition Sportswear", tier: 4, guidelines: [{ type: 'max_reputation', value: 65 }, { type: 'prefers_underdogs' }], baseAnnualValue: [150_000, 550_000], preferredType: 'Kit Supplier' },
    { id: 69, name: "Rise Coffee Co.", tier: 4, guidelines: [{ type: 'max_reputation', value: 55 }], baseAnnualValue: [50_000, 190_000], preferredType: 'Main Shirt' },
    { id: 70, name: "Vertex Solar", tier: 4, guidelines: [{ type: 'max_reputation', value: 62 }], baseAnnualValue: [125_000, 480_000], preferredType: 'Training Ground' },
    { id: 71, name: "Harbor Insurance", tier: 4, guidelines: [{ type: 'max_reputation', value: 60 }], baseAnnualValue: [100_000, 370_000], preferredType: 'Main Shirt' },
    { id: 72, name: "Precision Engineering", tier: 4, guidelines: [{ type: 'max_reputation', value: 63 }], baseAnnualValue: [140_000, 520_000], preferredType: 'Main Shirt' },
    { id: 73, name: "The Farmer's Market", tier: 4, guidelines: [{ type: 'max_reputation', value: 50 }], baseAnnualValue: [18_000, 85_000], preferredType: 'Main Shirt' },
    { id: 74, name: "County Council", tier: 4, guidelines: [{ type: 'max_reputation', value: 68 }], baseAnnualValue: [200_000, 700_000], preferredType: 'Stadium Naming Rights' },
    { id: 75, name: "First Call Plumbing", tier: 4, guidelines: [{ type: 'max_reputation', value: 55 }], baseAnnualValue: [48_000, 170_000], preferredType: 'Main Shirt' },
    { id: 76, name: "Jetstream Couriers", tier: 4, guidelines: [{ type: 'max_reputation', value: 60 }], baseAnnualValue: [98_000, 360_000], preferredType: 'Main Shirt' },
    { id: 77, name: "The Local Butcher", tier: 4, guidelines: [{ type: 'max_reputation', value: 53 }], baseAnnualValue: [28_000, 110_000], preferredType: 'Main Shirt' },
    { id: 78, name: "Sunrise Bakery", tier: 4, guidelines: [{ type: 'max_reputation', value: 54 }], baseAnnualValue: [32_000, 130_000], preferredType: 'Main Shirt' },
    { id: 79, name: "Community First Bank", tier: 4, guidelines: [{ type: 'max_reputation', value: 65 }], baseAnnualValue: [180_000, 650_000], preferredType: 'Main Shirt' },
    { id: 80, name: "City Airport", tier: 4, guidelines: [{ type: 'max_reputation', value: 66 }], baseAnnualValue: [220_000, 800_000], preferredType: 'Training Ground' }
];
